# Generated by Django 4.1.1 on 2022-10-04 04:46

import ckeditor_uploader.fields
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Contact',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('first_name', models.CharField(max_length=30)),
                ('last_name', models.CharField(max_length=30)),
                ('email', models.EmailField(max_length=50)),
                ('phone', models.PositiveIntegerField(max_length=10)),
                ('subject', models.CharField(max_length=50)),
                ('message', ckeditor_uploader.fields.RichTextUploadingField(max_length=500)),
            ],
        ),
    ]
