# Generated by Django 4.1.1 on 2022-10-01 12:52

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0004_alter_profile_user'),
    ]

    operations = [
        migrations.AlterField(
            model_name='profile',
            name='identity',
            field=models.FileField(blank=True, null=True, upload_to='identity/'),
        ),
    ]
