# Generated by Django 4.1.1 on 2022-10-01 13:05

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0005_alter_profile_identity'),
    ]

    operations = [
        migrations.AlterField(
            model_name='profile',
            name='avatar',
            field=models.ImageField(blank=True, default='default.png', null=True, upload_to='profile_avatar/'),
        ),
        migrations.AlterField(
            model_name='profile',
            name='identity',
            field=models.ImageField(blank=True, default='default.png', null=True, upload_to='identity/'),
        ),
    ]
