# Generated by Django 4.1.1 on 2022-10-02 08:41

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('shop', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='BookImages',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('image', models.ImageField(blank=True, null=True, upload_to='{book.title}/')),
                ('book', models.ForeignKey(default='default.png', on_delete=django.db.models.deletion.CASCADE, related_name='images', to='shop.book')),
            ],
        ),
    ]
