# Generated by Django 4.1.1 on 2022-10-02 09:20

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('shop', '0002_bookimages'),
    ]

    operations = [
        migrations.AlterField(
            model_name='bookimages',
            name='image',
            field=models.ImageField(blank=True, null=True, upload_to='book/'),
        ),
    ]
