# Generated by Django 4.1.1 on 2022-10-02 10:19

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('shop', '0006_author_slug'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='author',
            name='slug',
        ),
    ]
