# Generated by Django 4.1.1 on 2022-10-10 02:06

import ckeditor_uploader.fields
from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('shop', '0011_alter_book_author_alter_book_publisher'),
    ]

    operations = [
        migrations.AlterField(
            model_name='author',
            name='description',
            field=ckeditor_uploader.fields.RichTextUploadingField(max_length=300),
        ),
        migrations.AlterField(
            model_name='book',
            name='description',
            field=ckeditor_uploader.fields.RichTextUploadingField(max_length=500),
        ),
        migrations.AlterField(
            model_name='publisher',
            name='description',
            field=ckeditor_uploader.fields.RichTextUploadingField(max_length=500),
        ),
    ]
