# Generated by Django 4.1.1 on 2022-10-12 10:15

import ckeditor_uploader.fields
from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('shop', '0014_book_users_wishlist'),
    ]

    operations = [
        migrations.AddField(
            model_name='review',
            name='comment',
            field=ckeditor_uploader.fields.RichTextUploadingField(blank=True, max_length=500, null=True),
        ),
    ]
