# Generated by Django 4.1.1 on 2022-10-14 02:23

from django.db import migrations
import django_extensions.db.fields


class Migration(migrations.Migration):

    dependencies = [
        ('shop', '0022_genre_slug'),
    ]

    operations = [
        migrations.AlterField(
            model_name='genre',
            name='slug',
            field=django_extensions.db.fields.AutoSlugField(blank=True, editable=False, null=True, populate_from=('genre',), unique=True, verbose_name='slug'),
        ),
    ]
