# Generated by Django 4.1.1 on 2022-10-14 07:25

import ckeditor_uploader.fields
from django.db import migrations, models
import django.db.models.deletion
import django_extensions.db.fields
import phonenumber_field.modelfields


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Carrer',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=50)),
                ('description', models.CharField(blank=True, max_length=5000, null=True)),
                ('full_time', models.BooleanField(default=True)),
                ('part_time', models.BooleanField(default=False)),
                ('remote_time', models.BooleanField(default=False)),
                ('slug', django_extensions.db.fields.AutoSlugField(blank=True, editable=False, populate_from=('title',), unique=True, verbose_name='slug')),
            ],
        ),
        migrations.CreateModel(
            name='Company',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100)),
                ('description', ckeditor_uploader.fields.RichTextUploadingField(max_length=1000)),
                ('email', models.EmailField(max_length=254)),
                ('website', models.URLField()),
                ('phone', phonenumber_field.modelfields.PhoneNumberField(blank=True, max_length=128, null=True, region=None)),
                ('address', models.CharField(max_length=200)),
                ('logo', models.ImageField(blank=True, null=True, upload_to='company/logo')),
                ('logo_name', models.CharField(blank=True, max_length=50, null=True)),
                ('main_banner_image', models.ImageField(upload_to='company/MainBannerImage')),
                ('main_banner_name', models.CharField(blank=True, max_length=50, null=True)),
                ('main_banner_quote', models.CharField(blank=True, max_length=100, null=True)),
                ('main_banner_link', models.CharField(blank=True, max_length=100, null=True)),
                ('terms_and_conditions', models.CharField(blank=True, max_length=20000, null=True)),
                ('slug', django_extensions.db.fields.AutoSlugField(blank=True, editable=False, max_length=100, populate_from=('name',), unique=True, verbose_name='slug')),
            ],
        ),
        migrations.CreateModel(
            name='FAQ',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('question', models.CharField(blank=True, max_length=100, null=True)),
                ('answer', models.CharField(blank=True, max_length=1000, null=True)),
                ('company', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='company_faq', to='company.company')),
            ],
        ),
        migrations.CreateModel(
            name='CV',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('first_name', models.CharField(max_length=50)),
                ('last_name', models.CharField(max_length=50)),
                ('email', models.EmailField(max_length=50)),
                ('phone', phonenumber_field.modelfields.PhoneNumberField(blank=True, max_length=128, null=True, region=None)),
                ('address', models.CharField(max_length=200)),
                ('resume', models.FileField(upload_to='company/resume/')),
                ('carrer', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='carrer_cv', to='company.carrer')),
            ],
        ),
        migrations.CreateModel(
            name='CompanyPhoneNumber',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('phone', phonenumber_field.modelfields.PhoneNumberField(blank=True, max_length=128, null=True, region=None)),
                ('company', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='company_phone', to='company.company')),
            ],
        ),
        migrations.CreateModel(
            name='Achievement',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=200)),
                ('image', models.ImageField(blank=True, null=True, upload_to='company/achievement')),
                ('slug', django_extensions.db.fields.AutoSlugField(blank=True, editable=False, populate_from=('title',), unique=True, verbose_name='slug')),
                ('company', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='company_achievement', to='company.company')),
            ],
        ),
    ]
