# Generated by Django 4.1.1 on 2022-10-11 07:24

from django.db import migrations
import django_extensions.db.fields


class Migration(migrations.Migration):

    dependencies = [
        ('orders', '0005_alter_address_user'),
    ]

    operations = [
        migrations.RenameField(
            model_name='address',
            old_name='provinvce',
            new_name='province',
        ),
        migrations.AlterField(
            model_name='address',
            name='slug',
            field=django_extensions.db.fields.AutoSlugField(blank=True, editable=False, max_length=100, populate_from=('street_address', 'provinvce'), unique=True, verbose_name='slug'),
        ),
    ]
