# Generated by Django 4.1.1 on 2022-10-11 08:11

from django.db import migrations
import django_extensions.db.fields


class Migration(migrations.Migration):

    dependencies = [
        ('orders', '0006_rename_provinvce_address_province_alter_address_slug'),
    ]

    operations = [
        migrations.AlterField(
            model_name='address',
            name='slug',
            field=django_extensions.db.fields.AutoSlugField(blank=True, editable=False, max_length=100, populate_from=('street_address', 'province'), unique=True, verbose_name='slug'),
        ),
    ]
