# Generated by Django 4.1.1 on 2022-10-12 06:05

from django.db import migrations
import django_extensions.db.fields


class Migration(migrations.Migration):

    dependencies = [
        ('orders', '0012_cartitem_order'),
    ]

    operations = [
        migrations.AlterField(
            model_name='address',
            name='slug',
            field=django_extensions.db.fields.AutoSlugField(blank=True, editable=False, max_length=100, populate_from=('user.username', 'street_address', 'province'), unique=True, verbose_name='slug'),
        ),
    ]
