# Generated by Django 4.1.1 on 2022-11-26 21:16

from django.db import migrations, models
import django_extensions.db.fields


class Migration(migrations.Migration):

    dependencies = [
        ('orders', '0016_orderitem_remove_cartitem_book_remove_cartitem_cart_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='address',
            name='slug',
            field=django_extensions.db.fields.AutoSlugField(blank=True, editable=False, max_length=100, populate_from=('user__username', 'street_address', 'province'), unique=True, verbose_name='slug'),
        ),
        migrations.AlterField(
            model_name='order',
            name='order_status',
            field=models.CharField(choices=[('Order Received', 'Order Received'), ('Order Processing', 'Order Processing'), ('On The Way', 'On The Way'), ('Order Completed', 'Order Completed'), ('Order Canceled', 'Order Canceled')], default='Order Received', max_length=20),
        ),
    ]
