# Generated by Django 4.1.1 on 2022-11-27 02:27

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('orders', '0017_alter_address_slug_alter_order_order_status'),
    ]

    operations = [
        migrations.AddField(
            model_name='order',
            name='paid_price',
            field=models.DecimalField(decimal_places=2, default=0, max_digits=12),
        ),
    ]
